In [9]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("R:\Recommandation System\Data\content_based_recommendation_dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\R'
<>:1: SyntaxWarning: invalid escape sequence '\R'
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2864087578.py:1: SyntaxWarning: invalid escape sequence '\R'
  df = pd.read_csv("R:\Recommandation System\Data\content_based_recommendation_dataset.csv")

In [11]:
df

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations,Probability for the product to be recommended to the person
0,12,4,4.2,male,500,4.5,PUMA,0.80,200,No,winter,plains,0.90
1,8,2,3.8,female,3000,3.2,Lee,-0.40,300,Yes,monsoon,mountains,0.20
2,25,10,4.5,female,600,4.8,Head Hunters,0.60,1000,No,spring,plains,0.70
3,6,1,2.1,female,100,2.5,Johnson & Johnson,0.10,300,No,summer,coastal,0.10
4,18,5,4.7,male,2000,4.3,Wakefit,0.90,700,Yes,winter,plains,0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,5,1,1.8,male,200,2.0,Kama Ayurveda,-0.90,300,Yes,spring,coastal,0.01
1470,37,13,4.7,female,900,4.6,Johnson & Johnson,0.75,600,No,summer,plains,0.77
1471,22,8,3.9,male,4000,4.1,SleepyCat,0.60,900,Yes,winter,mountains,0.76
1472,40,15,4.8,female,700,4.9,Flying Machine,0.90,500,No,summer,mountains,0.82
1473,12,4,3.0,male,5000,3.2,Head Hunters,0.10,600,No,summer,plains,0.41

In [94]:
def Simplify_split(df):
    df.loc[df.Gender == "male", ['Gender']] = 1
    df.loc[df.Gender == "female", ['Gender']] = 0 # Managing Gender

    season = {
    "summer" : 0,
    "winter" : 1,
    "monsoon" : 2,
    "spring" : 3

    } # Managing Seasons

    df['Season'] = df['Season'].replace(season) # Season Replaced

    # Managing Geographical Location
    df['Geographical locations'] = df['Geographical locations'].replace({
    "plains" : 0,
    "mountains" : 1,
    "coastal" : 2
    })

    # Managing Holidays
    df['Holiday'] = df['Holiday'].replace({
        "Yes" : 1,
        "No" : 0
    })

    
    brands = {'PUMA': 0, 'Lee': 1, 'Head Hunters': 2, 'Johnson & Johnson': 3, 'Wakefit': 4, 'Dabur Chyawanprash': 5, 'Manyavar Mohey': 6, 'Pepperfry': 7, 'Lee Cooper': 8, 'Libram': 9, 'Flying Machine': 10, 'SleepyCat': 11, 'Streax': 12, 'Lakme Ayurveda': 13, 'Forest Essentials': 14, 'Dove Hair': 15, 'Pepe Jeans London': 16, 'The Moms Co.': 17, 'Himalaya Liv.52': 18, 'Wildcraft': 19, 'Godrej Interio': 20, 'Patanjali Ayurved (Health Care)': 21, 'Lijoba': 22, 'Moov': 23, 'Kama Ayurveda': 24, 'Urban Ladder': 25, 'Allen Solly Woman': 26, 'Max': 27, 'Head & Shoulders': 28, 'Fastrack': 29, 'Sugar Cosmetics': 30, 'Parachute': 31, 'Dettol': 32, 'AmazonBasics': 33, 'U.S. Polo Assn. Women': 34, 'Khadi Essentials': 35, 'Whisper': 36, 'Levis Strauss & Co.': 37, 'Wild Stone': 38, 'Biovea': 39, 'Vero Moda': 40, 'Zandu': 41, 'HRX': 42, 'Mothercare': 43, 'Duroflex': 44, 'Spyker': 45, 'Stayfree': 46, 'Baidyanath': 47}

    # Companies SUpported
    # replacing

    df['Brand of the product'] = df['Brand of the product'].replace(brands)

    return df.astype(float)

In [13]:
import tensorflow as tf

c:\Users\Radhe-Radhe\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [14]:
data = df[3:9]

In [15]:
data = data.drop(columns="Probability for the product to be recommended to the person")

In [16]:
data

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations
3,6,1,2.1,female,100,2.5,Johnson & Johnson,0.10,300,No,summer,coastal
4,18,5,4.7,male,2000,4.3,Wakefit,0.90,700,Yes,winter,plains
5,0,0,0.0,male,1000,0.0,Dabur Chyawanprash,-0.70,1000,No,winter,mountains
6,38,15,4.9,female,700,4.9,Manyavar Mohey,0.95,700,No,summer,plains
7,7,3,3.4,male,5000,3.7,Pepperfry,0.20,900,No,winter,coastal
8,4,0,1.5,male,900,1.8,Lee Cooper,-0.30,400,No,monsoon,mountains

In [17]:
df_sorted = Simplify_split(data)

C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Season'] = df['Season'].replace(season) # Season Replaced
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Geographical locations'] = df['Geographical locations'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Holiday'] = df['Holiday'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:34: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Brand of the product'] = df['Brand of the product'].replace(brands)

In [18]:
df_sorted

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations
3,6,1,2.1,0,100,2.5,3,0.10,300,0,0,2
4,18,5,4.7,1,2000,4.3,4,0.90,700,1,1,0
5,0,0,0.0,1,1000,0.0,5,-0.70,1000,0,1,1
6,38,15,4.9,0,700,4.9,6,0.95,700,0,0,0
7,7,3,3.4,1,5000,3.7,7,0.20,900,0,1,2
8,4,0,1.5,1,900,1.8,8,-0.30,400,0,2,1

In [21]:
model = tf.keras.models.load_model(r"R:\Recommandation System\Model\Recormandation_System.keras")

In [22]:
preds = model.predict(df_sorted).reshape(-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 367ms/step

In [23]:
predictions = np.where(preds > 0.5, 1, 0)

In [24]:
predictions

array([0, 1, 0, 1, 0, 0])

In [25]:
df[3:9]

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations,Probability for the product to be recommended to the person
3,6,1,2.1,female,100,2.5,Johnson & Johnson,0.10,300,No,summer,coastal,0.10
4,18,5,4.7,male,2000,4.3,Wakefit,0.90,700,Yes,winter,plains,0.80
5,0,0,0.0,male,1000,0.0,Dabur Chyawanprash,-0.70,1000,No,winter,mountains,0.00
6,38,15,4.9,female,700,4.9,Manyavar Mohey,0.95,700,No,summer,plains,1.00
7,7,3,3.4,male,5000,3.7,Pepperfry,0.20,900,No,winter,coastal,0.30
8,4,0,1.5,male,900,1.8,Lee Cooper,-0.30,400,No,monsoon,mountains,0.05

In [26]:
df

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations,Probability for the product to be recommended to the person
0,12,4,4.2,male,500,4.5,PUMA,0.80,200,No,winter,plains,0.90
1,8,2,3.8,female,3000,3.2,Lee,-0.40,300,Yes,monsoon,mountains,0.20
2,25,10,4.5,female,600,4.8,Head Hunters,0.60,1000,No,spring,plains,0.70
3,6,1,2.1,female,100,2.5,Johnson & Johnson,0.10,300,No,summer,coastal,0.10
4,18,5,4.7,male,2000,4.3,Wakefit,0.90,700,Yes,winter,plains,0.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,5,1,1.8,male,200,2.0,Kama Ayurveda,-0.90,300,Yes,spring,coastal,0.01
1470,37,13,4.7,female,900,4.6,Johnson & Johnson,0.75,600,No,summer,plains,0.77
1471,22,8,3.9,male,4000,4.1,SleepyCat,0.60,900,Yes,winter,mountains,0.76
1472,40,15,4.8,female,700,4.9,Flying Machine,0.90,500,No,summer,mountains,0.82
1473,12,4,3.0,male,5000,3.2,Head Hunters,0.10,600,No,summer,plains,0.41

In [27]:
df.columns

Index(['Number of clicks on similar products',
       'Number of similar products purchased so far',
       'Average rating given to similar products', 'Gender',
       'Median purchasing price (in rupees)', 'Rating of the product',
       'Brand of the product', 'Customer review sentiment score (overall)',
       'Price of the product', 'Holiday', 'Season', 'Geographical locations',
       'Probability for the product to be recommended to the person'],
      dtype='object')

In [53]:
columnsss = df.columns

In [ ]:
def Simplify_split_arr(array_2d):
    df = pd.DataFrame(array_2d.T, columns=columnsss[:-1])
    
    return Simplify_split(df)

In [84]:
inp = np.array([
    [10, 8],
    [3, 1],
    [4.6, 4.3],
    ['male', 'female'],
    [500, 200],
    [4.3, 5],
    ['PUMA', 'PUMA'],
    [0.82, 0.9],
    [600, 700],
    ['Yes', "No"],
    ['summer', 'winter'],
    ['plains', 'plains'],
])

In [80]:
Simplify_split_arr(inp)

C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Season'] = df['Season'].replace(season) # Season Replaced
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Geographical locations'] = df['Geographical locations'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:34: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Brand of the product'] = df['Brand of the product'].replace(brands)

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations
0,10,3,4.6,1,500,4.3,0,0.82,600,1,0,0
1,8,1,4.3,0,200,5,0,0.9,700,NO,1,0

In [68]:
pd.DataFrame(inp.T, columns=list(columnsss)[:-1] )

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations
0,10,3,4.6,male,500,4.3,PUMA,0.82,600,Yes,summer,plains

In [46]:
len(columnsss[::-1])

13

In [47]:
len(inp)

11

In [50]:
len(inp)

12

In [51]:
len(columnsss[::-1])

13

In [52]:
columnsss[::-1]

array(['Probability for the product to be recommended to the person',
       'Geographical locations', 'Season', 'Holiday',
       'Price of the product',
       'Customer review sentiment score (overall)',
       'Brand of the product', 'Rating of the product',
       'Median purchasing price (in rupees)', 'Gender',
       'Average rating given to similar products',
       'Number of similar products purchased so far',
       'Number of clicks on similar products'], dtype=object)

In [54]:
columnsss[::-1]

Index(['Probability for the product to be recommended to the person',
       'Geographical locations', 'Season', 'Holiday', 'Price of the product',
       'Customer review sentiment score (overall)', 'Brand of the product',
       'Rating of the product', 'Median purchasing price (in rupees)',
       'Gender', 'Average rating given to similar products',
       'Number of similar products purchased so far',
       'Number of clicks on similar products'],
      dtype='object')

In [55]:
len(columnsss[::-1])

13

In [56]:
list(columnsss)[::-1]

['Probability for the product to be recommended to the person',
 'Geographical locations',
 'Season',
 'Holiday',
 'Price of the product',
 'Customer review sentiment score (overall)',
 'Brand of the product',
 'Rating of the product',
 'Median purchasing price (in rupees)',
 'Gender',
 'Average rating given to similar products',
 'Number of similar products purchased so far',
 'Number of clicks on similar products']

In [58]:
len(inp.T)

1

In [61]:
tf = pd.DataFrame(inp.T)

In [62]:
tf.columns = list(columnsss)[::-1]

ValueError: Length mismatch: Expected axis has 12 elements, new values have 13 elements

In [63]:
tf

   0  1    2     3    4    5     6     7    8    9       10      11
0  10  3  4.6  male  500  4.3  PUMA  0.82  600  Yes  summer  plains

In [67]:
list(columnsss)[:-1]

['Number of clicks on similar products',
 'Number of similar products purchased so far',
 'Average rating given to similar products',
 'Gender',
 'Median purchasing price (in rupees)',
 'Rating of the product',
 'Brand of the product',
 'Customer review sentiment score (overall)',
 'Price of the product',
 'Holiday',
 'Season',
 'Geographical locations']

In [ ]:
model.predict()

C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2507110540.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Season'] = df['Season'].replace(season) # Season Replaced
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2507110540.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Geographical locations'] = df['Geographical locations'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2507110540.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Holiday'] = df['Holiday'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2507110540.py:35: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Brand of the product'] = df['Brand of the product'].replace(brands)

ValueError: Invalid dtype: object

In [85]:
dtf = Simplify_split_arr(inp)

C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Season'] = df['Season'].replace(season) # Season Replaced
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Geographical locations'] = df['Geographical locations'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Holiday'] = df['Holiday'].replace({
C:\Users\Radhe-Radhe\AppData\Local\Temp\ipykernel_3320\2930003243.py:34: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Brand of the product'] = df['Brand of the product'].replace(brands)

In [86]:
dtf

,Number of clicks on similar products,Number of similar products purchased so far,Average rating given to similar products,Gender,Median purchasing price (in rupees),Rating of the product,Brand of the product,Customer review sentiment score (overall),Price of the product,Holiday,Season,Geographical locations
0,10,3,4.6,1,500,4.3,0,0.82,600,1,0,0
1,8,1,4.3,0,200,5,0,0.9,700,0,1,0

In [93]:
model.predict(dtf)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step

array([[0.5268344 ],
       [0.10274042]], dtype=float32)

In [89]:
dtf.describe()

       Brand of the product   Holiday    Season  Geographical locations
count                   2.0  2.000000  2.000000                     2.0
mean                    0.0  0.500000  0.500000                     0.0
std                     0.0  0.707107  0.707107                     0.0
min                     0.0  0.000000  0.000000                     0.0
25%                     0.0  0.250000  0.250000                     0.0
50%                     0.0  0.500000  0.500000                     0.0
75%                     0.0  0.750000  0.750000                     0.0
max                     0.0  1.000000  1.000000                     0.0

In [90]:
dtf.Gender.describe

<bound method NDFrame.describe of 0    1
1    0
Name: Gender, dtype: object>

In [92]:
dtf = dtf.astype(float)